/**
 * Self Description JSON Schema v1.1.0
 * Licensed under MIT License
 * (c) Copyright 2018-2019 W3plan Technologies, https://www.w3plan.net/
 */
(function(){var l=function(){};l.consoleMessage=function(d,e,f,h){h=h||"#000";var g=new Date;f=f?" - Line: "+f:"";3==d||"string"==typeof d&&"notice"==d.toLowerCase()?console.log("%c "+g.getHours()+":"+g.getMinutes()+":"+g.getSeconds()+" - Notice:\n"+e+f,"color: "+h):2==d||"string"==typeof d&&"warning"==d.toLowerCase()?console.log("%c "+g.getHours()+":"+g.getMinutes()+":"+g.getSeconds()+" - Warning:\n"+e+f,"color: "+h):console.log("%c "+g.getHours()+":"+g.getMinutes()+":"+g.getSeconds()+" - Error:\n"+
e+f,"color: "+h)};l.printMessage=function(d,e,f,h){h=h||"#ff0000";var g=new Date;f=f?" - Line: "+f:"";var m="";m=3==d||"string"==typeof d&&"notice"==d.toLowerCase()?g.getHours()+":"+g.getMinutes()+":"+g.getSeconds()+" - Notice:<br>"+e+f:2==d||"string"==typeof d&&"warning"==d.toLowerCase()?g.getHours()+":"+g.getMinutes()+":"+g.getSeconds()+" - Warning:<br>"+e+f:g.getHours()+":"+g.getMinutes()+":"+g.getSeconds()+" - Error:<br>"+e+f;d=document.createElement("div");d.innerHTML='<div style="width:600px; padding:20px; margin:150px auto; word-wrap:break-word; background-color:#efefef; color:'+
h+'">'+m+"</div>";d.style.cssText="text-align:center";document.getElementsByTagName("body")[0]?document.getElementsByTagName("body")[0].appendChild(d):window.onload=function(){alert(m)}};var w=function(){var d=function(c){return Number(c)===c&&0===c%1},e=function(c){return Number(c)===c&&0!==c%1},f=function(c){return"number"===typeof c&&!isNaN(c)},h=function(c){return"string"===typeof c&&!isNaN(c)&&c==+c},g=function(c){return h(c)&&/e\+|-/gi.test(c)},m=function(c){return h(c)&&/^-?0x[0-9a-f]+$/i.test(c)},
u=function(c){return h(c)&&/^-?0[0-7]+$/i.test(c)},p=function(c){for(var d in c)if(c.hasOwnProperty(d))return!1;return!0},k=function(c){return"string"===typeof c||c instanceof String},q=function(c){return"[object Object]"===Object.prototype.toString.call(c)},r=function(c,e,a){var b=[],n;for(n in c)"enumeration"==n?Array.isArray(c.enumeration)&&-1!==c.enumeration.indexOf(a)?b.push(1):b.push(0):"pattern"==n?k(a)&&"[object RegExp]"===Object.prototype.toString.call(new RegExp(a))&&c.pattern.test(a)?b.push(1):
b.push(0):"length"==n?d(a)&&a.length===c.length?b.push(1):b.push(0):"maxLength"==n?d(a)&&a.length<=c.maxLength?b.push(1):b.push(0):"minLength"==n?d(a)&&a.length>=c.minLength?b.push(1):b.push(0):"totalDigits"==n?f(a)&&a.toString().repalce(".","").length===c.totalDigits&&0<c.totalDigits?b.push(1):b.push(0):"fractionDigits"==n?f(a)&&a.toString().split(".")[1].length===c.fractionDigits?b.push(1):b.push(0):"minExclusive"==n?f(a)&&a>c.minExclusive?b.push(1):b.push(0):"maxExclusive"==n?f(a)&&a<c.maxExclusive?
b.push(1):b.push(0):"minInclusive"==n?f(a)&&a>=c.minInclusive?b.push(1):b.push(0):"maxInclusive"==n&&(f(a)&&a<=c.maxInclusive?b.push(1):b.push(0));if(0<b.length&&-1===b.indexOf(0))return!0;l.printMessage(2,"The value "+a+" of member "+e+" againsts constraint "+JSON.stringify(c));return!1},t=function(c,v,a){var b=!1;switch(c){case "string":k(a)&&(b=!0);break;case "emptyString":k(a)&&!a&&(b=!0);break;case "numberString":h(a)&&(b=!0);break;case "integerString":k(a)&&d(+a)&&(b=!0);break;case "floatString":k(a)&&
e(+a)&&(b=!0);break;case "fractionString":/^[1-9][0-9]*\/[1-9][0-9]*$/.test(a)&&(b=!0);break;case "exponentString":g(a)&&(b=!0);break;case "asciiString":"string"===typeof a&&/^[\x00-\xFF]+$/.test(a)&&(b=!0);break;case "hexString":m(a)&&(b=!0);break;case "octalString":u(a)&&(b=!0);break;case "jsonString":try{JSON.parse(a)}catch(n){l.printMessage(2,a+" againsts type "+c),b=!1}b=!0;break;case "normalizedString":h(a)&&a.replace(/[\t\r\n]/g,"")==a&&(b=!0);break;case "regExpString":k(a)&&"[object RegExp]"===
Object.prototype.toString.call(new RegExp(a))&&(b=!0);break;case "url":/^(ftp:|ftps:|ws:|wss:|http:|https:)?(\/\/)((([a-z\d]([a-z\d-]*[a-z\d])*)\.)+[a-z]{2,}|((\d{1,3}\.){3}\d{1,3}))(:\d+)?(\/[-a-z\d%_.~+=]*)*(\?[;&a-z\d%_.~+=-]*)?(#[-a-z\d_]*)?$/i.test(a)&&(b=!0);break;case "urlEncoded":encodeURIComponent(decodeURIComponent(a))===a&&(b=!0);break;case "email":/^(?=.{1,254}$)(?=.{1,64}@)[-!#$%&'*+\/0-9=?A-Z^_`a-z{|}~]+(\.[-!#$%&'*+\/0-9=?A-Z^_`a-z{|}~]+)*@[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*$/.test(a)&&
(b=!0);break;case "ipv4":/^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/.test(a)&&(b=!0);break;case "base64":try{window.atob(a)}catch(n){l.printMessage(2,a+" against type "+c),b=!1}b=!0;break;case "uuid":/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$/.test(a)&&(b=!0);break;case "unicodeString":"string"===typeof a&&/[^\u0000-\u10FFFF]+$/.test(a)&&(b=!0);break;case "country":-1!=="AF AX AL DZ AS AD AO AI AQ AG AR AM AW AU AT AZ BS BH BD BB BY BE BZ BJ BM BT BO BQ BA BW BV BR IO BN BG BF BI KH CM CA CV KY CF TD CL CN CX CC CO KM CG CD CK CR CI HR CU CW CY CZ DK DJ DM DO EC EG SV GQ ER EE ET FK FO FJ FI FR GF PF TF GA GM GE DE GH GI GR GL GD GP GU GT GG GN GW GY HT HM VA HN HK HU IS IN ID IR IQ IE IM IL IT JM JP JE JO KZ KE KI KP KR KW KG LA LV LB LS LR LY LI LT LU MO MK MG MW MY MV ML MT MH MQ MR MU YT MX FM MD MC MN ME MS MA MZ MM NA NR NP NL NC NZ NI NE NG NU NF MP NO OM PK PW PS PA PG PY PE PH PN PL PT PR QA RE RO RU RW BL SH KN LC MF PM VC WS SM ST SA SN RS SC SL SG SX SK SI SB SO ZA GS SS ES LK SD SR SJ SZ SE CH SY TW TJ TZ TH TL TG TK TO TT TN TR TM TC TV UG UA AE GB US UM UY UZ VU VE VN VG VI WF EH YE ZM ZW".split(" ").indexOf(a.trim().toUpperCase())&&
(b=!0);break;case "language":/^[a-z]{2,3}(?:-[A-Z]{2,3}(?:-[a-zA-Z]{4})?)?$/.test(a)&&(b=!0);break;case "cssString":/^(?:\s*[\S ]+\s*{[^}]*})+/.test(a)&&(b=!0);break;case "hexColor":/^#([a-f0-9]{3}){1,2}$/i.test(a)&&(b=!0);break;case "rgbColor":/^rgb(a)?\(\d{1,3},\s?\d{1,3},\s?\d{1,3}\)$/i.test(a)&&(b=!0);break;case "cssRatio":/^[1-9][0-9]*\/[1-9][0-9]*$/.test(a)&&(b=!0);break;case "cssLength":!k(a)||-1==="ch em ex rem vh vw px mm cm in pt pc".split(" ").indexOf(a.trim().slice(-2).toLowerCase())&&
-1===["vmin","vmax"].indexOf(a.trim().slice(-4).toLowerCase())||(b=!0);break;case "cssAngle":!k(a)||-1===["deg","rad"].indexOf(a.trim().slice(-3).toLowerCase())&&-1===["grad","turn"].indexOf(a.trim().slice(-4).toLowerCase())||(b=!0);break;case "cssResolution":!k(a)||-1===["dpcm","dppx"].indexOf(a.trim().slice(-4).toLowerCase())&&"dpi"!==a.trim().slice(-3).toLowerCase()||(b=!0);break;case "cssFrequency":!k(a)||"hz"!==a.trim().slice(-2).toLowerCase()&&"khz"!==a.trim().slice(-3).toLowerCase()||(b=!0);
break;case "cssTime":!k(a)||"s"!==a.trim().slice(-1).toLowerCase()&&"ms"!==a.trim().slice(-2).toLowerCase()||(b=!0);break;case "cssPercentage":k(a)&&"%"===a.trim().slice(-1).toLowerCase()&&(b=!0);break;case "cssPosition":-1!==["static","relative","absolute","sticky","fixed"].indexOf(a.trim().toLowerCase())&&(b=!0);break;case "date":"string"===typeof a&&!isNaN(new Date(a))&&/^\d{4}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$/.test(a)&&(b=!0);break;case "time":k(a)&&/^([0-1][0-9]|2[0-4]):([0-5][0-9]):[0-5][0-9](.\d{3})?$/.test(a)&&
(b=!0);break;case "dateTime":k(a)&&/^\d{4}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01]) ([0-1][0-9]|2[0-4]):([0-5][0-9]):[0-5][0-9](.\d{3})?$/.test(a)&&(b=!0);break;case "gYear":k(a)&&/^\d{4}$/.test(a)&&(b=!0);break;case "gMonth":k(a)&&/^--(0[1-9]|1[012])--$/.test(a)&&(b=!0);break;case "gDay":k(a)&&/^---(0[1-9]|[12][0-9]|3[01])$/.test(a)&&(b=!0);break;case "gYearMonth":k(a)&&/^\d{4}-(0[1-9]|1[012])$/.test(a)&&(b=!0);break;case "gMonthDay":k(a)&&/^--(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$/.test(a)&&
(b=!0);break;case "integer":d(a)&&(b=!0);break;case "float":e(a)&&(b=!0);break;case "exponent":f(a)&&/^e\+|-/i.test(a)&&(b=!0);break;case "zero":f(a)&&0===a&&(b=!0);break;case "positiveInteger":d(a)&&0<a&&(b=!0);break;case "nonNegativeInteger":d(a)&&0<=a&&(b=!0);break;case "negativeInteger":d(a)&&0>a&&(b=!0);break;case "nonPositiveInteger":d(a)&&0>=a&&(b=!0);break;case "positiveFloat":e(a)&&0<a&&(b=!0);break;case "nonNegativeFloat":e(a)&&0<=a&&(b=!0);break;case "negativeFloat":e(a)&&0>a&&(b=!0);break;
case "nonPositiveFloat":e(a)&&0>=a&&(b=!0);break;case "finiteNumber":isFinite(a)&&(b=!0);break;case "number":f(a)&&(b=!0);break;case "true":"boolean"===typeof a&&!0===a&&(b=!0);break;case "false":"boolean"===typeof a&&!1===a&&(b=!0);break;case "boolean":"boolean"===typeof a&&(b=!0);break;case "null":null===a&&(b=!0);break;case "emptyObject":p(a)&&(b=!0);break;case "serializeObject":q(a)&&(b=!0);break;case "emptyArray":Array.isArray(a)&&0===a.length&&(b=!0);break;case "stringArray":Array.isArray(a)&&
a.every(function(a){return k(a)})&&(b=!0);break;case "positiveIntegerArray":Array.isArray(a)&&a.every(function(a){return d(a)&&0<a})&&(b=!0);break;case "nonNegativeIntegerArray":Array.isArray(a)&&a.every(function(a){return d(a)&&0<=a})&&(b=!0);break;case "negativeIntegerArray":Array.isArray(a)&&a.every(function(a){return d(a)&&0>a})&&(b=!0);break;case "integerArray":Array.isArray(a)&&a.every(function(a){return d(a)})&&(b=!0);break;case "numberArray":Array.isArray(a)&&a.every(function(a){return f(a)})&&
(b=!0);break;case "array":Array.isArray(a)&&(b=!0)}if(b)return!0;l.printMessage(2,"The value "+a+" of member "+v+" againsts type "+c);return!1};this.validateSdjs=function(c,d){d=d||{};for(var a in c)if(c.hasOwnProperty(a))if("_pfGlobal"===a&&q(c._pfGlobal)&&(d=c._pfGlobal),q(c[a]))this.validateSdjs(c[a],d);else if(Array.isArray(c[a]))for(var b=0,e=c[a].length;b<e;b++)if(q(c[a][b])||Array.isArray(c[a][b]))this.validateSdjs(c[a][b],d);else{if(c.hasOwnProperty(a+"_pfidx")){var f=null;c[a+"_pfidx"].hasOwnProperty("all")&&
"undefined"!==typeof c[a+"_pfidx"].all.type?f="all":c[a+"_pfidx"].hasOwnProperty(b)&&"undefined"!==typeof c[a+"_pfidx"][b].type&&(f=b);null!==f&&(t(c[a+"_pfidx"][f].type,b,c[a][b]),"undefined"!==typeof c[a+"_pfidx"][f].constraint&&r(c[a+"_pfidx"][f].constraint,b,c[a][b]))}}else c.hasOwnProperty(a+"_pfsch")&&k(c[a+"_pfsch"])&&""!==c[a+"_pfsch"]&&d.hasOwnProperty(a+"_"+c[a+"_pfsch"])&&"undefined"!==typeof d[a+"_"+c[a+"_pfsch"]].type?(t(d[a+"_"+c[a+"_pfsch"]].type,a,c[a]),"undefined"!==typeof d[a+"_"+
c[a+"_pfsch"]].constraint&&r(d[a+"_"+c[a+"_pfsch"]].constraint,a,c[a])):c.hasOwnProperty(a+"_pfsch")&&"undefined"!==typeof c[a+"_pfsch"].type?(t(c[a+"_pfsch"].type,a,c[a]),"undefined"!==typeof c[a+"_pfsch"].constraint&&r(c[a+"_pfsch"].constraint,a,c[a])):6<a.length&&"_pfsch"===a.slice(-6)&&"implied"===c[a].presence&&"undefined"!==typeof c[a].type&&!c.hasOwnProperty(a.slice(0,-6))&&(b="",e=null,c.hasOwnProperty(a.slice(0,-6)+"_default")?(b=a.slice(0,-6)+"_default",e=c[b]):c.hasOwnProperty(a.slice(0,
-6)+"_fixed")&&(b=a.slice(0,-6)+"_fixed",e=c[b]),null!==e&&(t(c[a].type,b,e),"undefined"!==typeof c[a].constraint&&r(c[a].constraint,b,e)))}};this.sdjs=new function(d){w.apply(this,arguments);this.TITLE="Self-Description JSON Schema";this.DESCRIPTION="The JavaScript Library for JSON description and constraints";this.VERSION=d;this.COPYRIGHT="Copyright 2018 W3plan Technologies";this.checkJsonSupport=function(){if(!window.JSON||"function"!==typeof window.JSON.parse)throw Error("Your browser doesn't support JSON");
};this.boxMessage=function(d,f,h){l.printMessage(d,f,h||"")};this.consoleMessage=function(d,f,h,g){l.consoleMessage(d,f,h||"",g||"")}}("Version 1.0.1");String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});Array.prototype.indexOf||(Array.prototype.indexOf=function(d,e){void 0===e&&(e=0);0>e&&(e+=this.length);0>e&&(e=0);for(var f=this.length;e<f;e++)if(e in this&&this[e]===d)return e;return-1});Array.prototype.lastIndexOf||(Array.prototype.lastIndexOf=function(d,
e){void 0===e&&(e=this.length-1);0>e&&(e+=this.length);e>this.length-1&&(e=this.length-1);for(e++;0<e--;)if(e in this&&this[e]===d)return e;return-1});Array.prototype.every||(Array.prototype.every=function(d,e){var f=this.length;e=e?e:void 0;for(var h=0;h<f;h++)if(!d.call(e,this[h],h,this))return!1;return!0});Array.isArray||(Array.isArray=function(d){return"[object Array]"===Object.prototype.toString.call(d)});window.btoa||(window.btoa=function(d){var e=0,f=0,h=[];if(!d)return d;d+="";do{var g=d.charCodeAt(e++);
var m=d.charCodeAt(e++);var l=d.charCodeAt(e++);var p=g<<16|m<<8|l;g=p>>18&63;m=p>>12&63;l=p>>6&63;p&=63;h[f++]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(m)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(l)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(p)}while(e<d.length);e=h.join("");d=d.length%3;return(d?e.slice(0,d-3):e)+"===".slice(d||
3)});window.atob||(window.atob=function(d){var e=0,f=0,h=[];if(!d)return d;d+="";do{var g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(d.charAt(e++));var m="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(d.charAt(e++));var l="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(d.charAt(e++));var p="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(d.charAt(e++));var k=g<<18|m<<12|l<<6|p;g=k>>
16&255;m=k>>8&255;k&=255;64==l?h[f++]=String.fromCharCode(g):64==p?h[f++]=String.fromCharCode(g,m):h[f++]=String.fromCharCode(g,m,k)}while(e<d.length);return h.join("").replace(/\0+$/,"")});window.console||(window.console={});window.console.log||(window.console.log=function(){})})();
